package GUI;

import java.awt.Component;
import java.util.ArrayList;

import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import json.Review;
import DB.ManageReviews;
import Engine.Engine;
import Engine.WordTopic;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class Businesses extends javax.swing.JFrame {

	public WordTopic word;
	public ArrayList<Review> reviewsArr;

	private ArrayList data = null;

	private Object[][] tableData;

	public ArrayList getData() {
		return data;
	}

	public void setData(ArrayList data) {
		this.data = data;
	}

	private DefaultTableModel tableModel;

	Object[][] reviews = { { null, null, null, null} };

	/**
	 * Creates new form Reviews2
	 */

	public Businesses(WordTopic word, ArrayList<Review> reviewsArr) {
		this.word = word;
		this.reviewsArr = reviewsArr;
		SwingUtilities.invokeLater(doWorkRunnable);
		initComponents();
		this.setSize(GUIFunctions.getWindowWidth(),
				GUIFunctions.getWindowHeight());
		updateRowHeights();
		resizeColumns();
		GUIFunctions.addResizeEvent(this);
	}

	Runnable doWorkRunnable = new Runnable() {
		@Override
		public void run() {
			initReviews();
			tableModel = new javax.swing.table.DefaultTableModel(tableData,
					new String[] { "#", "Name", "ID", "Value" });
			jTable1.setModel(tableModel);
			tableModel.fireTableDataChanged();
		}
	};

	private void initReviews() {
		this.data = GUIFunctions.doRankingOfBusinesses(word, reviewsArr);
		tableData = new Object[data.size()][];
		for (int i = 0; i < data.size(); i++) {
			Object[] obj = (Object[]) data.get(i);
			tableData[i] = new Object[] { i + 1, obj[2], obj[1], obj[0] };
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelWord = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemRestart = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelWord.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		if (word != null) {
			jLabelWord.setText(word.word);
		} else {
			jLabelWord.setText("Word");
		}

		jTable1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		tableModel = new javax.swing.table.DefaultTableModel(reviews,
				new String[] {  "#", "Name", "ID", "Value" });
		jTable1.setRowHeight(30);
		jTable1.setModel(tableModel);
		// jTable1.getColumnModel().getColumn(1).setCellRenderer(new
		// ReviewRowRenderer());

		jScrollPane1.setViewportView(jTable1);

		jMenu1.setText("File");

		jMenuItemRestart.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jMenuItemRestart.setText("Restart");
		jMenuItemRestart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemRestartActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemRestart);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 586,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 297,
								Short.MAX_VALUE).addContainerGap()));

	
		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void updateRowHeights() {
		for (int row = 0; row < jTable1.getRowCount(); row++) {
			int rowHeight = jTable1.getRowHeight();

			Component comp = jTable1.prepareRenderer(
					jTable1.getCellRenderer(row, 1), row, 1);
			rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);

			jTable1.setRowHeight(row, rowHeight);
		}
	}

	private void resizeColumns() {
		float[] columnWidthPercentage = { 10.0f, 50.0f, 10.0f, 10.0f, 10.0f,
				10.0f };
		int tW = jTable1.getWidth();
		TableColumn column;
		TableColumnModel jTableColumnModel = jTable1.getColumnModel();
		int cantCols = jTableColumnModel.getColumnCount();
		for (int i = 0; i < cantCols; i++) {
			column = jTableColumnModel.getColumn(i);
			int pWidth = Math.round(columnWidthPercentage[i] * tW);
			column.setPreferredWidth(pWidth);
		}
	}

	private void jMenuItemRestartActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.restart(this);
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabelWord;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemRestart;

	// End of variables declaration
}
