package GUI;

import java.awt.Component;
import java.util.ArrayList;

import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import json.Review;
import Engine.Engine;
import Engine.WordTopic;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class Reviews extends javax.swing.JFrame {

	private boolean allReviews;

	private String category;
	private double lat;
	private double lng;
	
	private WordTopic word = null;
	
	ArrayList<Review> reviewsArr = null;
	
	private DefaultTableModel tableModel;

	public boolean isAllReviews() {
		return allReviews;
	}

	public void setAllReviews(boolean allReviews) {
		this.allReviews = allReviews;
	}

	Object[][] reviews = { { null, null, null, null, null, null } };

	/**
	 * Creates new form Reviews2
	 */
	public Reviews(String category, double lat, double lng) {
		allReviews = false;
		this.category = category;
		this.lat = lat;
		this.lng = lng;
		initComponents();
		this.setSize(GUIFunctions.getWindowWidth(),
				GUIFunctions.getWindowHeight());
		updateRowHeights();
		resizeColumns();
		GUIFunctions.addResizeEvent(this);
	}

	public Reviews(WordTopic word) {
		allReviews = false;
		this.word = word;
		SwingUtilities.invokeLater(doWorkRunnable);
		initComponents();
		this.setSize(GUIFunctions.getWindowWidth(),
				GUIFunctions.getWindowHeight());
		updateRowHeights();
		resizeColumns();
		GUIFunctions.addResizeEvent(this);
	}

	public Reviews(boolean allReview, String category, double lat, double lng) {
		this.allReviews = allReview;
		this.category = category;
		this.lat = lat;
		this.lng = lng;
		if (allReview) {
			SwingUtilities.invokeLater(doWorkRunnable);
		}
		initComponents();
		this.setSize(GUIFunctions.getWindowWidth(),
				GUIFunctions.getWindowHeight());
		updateRowHeights();
		resizeColumns();
		GUIFunctions.addResizeEvent(this);
	}

	Runnable doWorkRunnable = new Runnable() {
		@Override
		public void run() {
			initReviews();
			tableModel = new javax.swing.table.DefaultTableModel(reviews,
					new String[] { "#", "Review", "Useful votes", "Funny votes",
					"Cool votes", "Stars" });
			jTable1.setModel(tableModel);
			tableModel.fireTableDataChanged();
			System.out.println(reviews.length);
		}
	};

	private void initReviews() {
		if (allReviews) {
			reviewsArr = Engine.filterReviews(category, lat, lng);	
		} else {
			reviewsArr = Engine.getReviewsOfWord(this.word);
		}
		reviews = new Object[reviewsArr.size()][6];
		for (int i = 0; i < reviewsArr.size(); i++) {
			Review review = reviewsArr.get(i);
			reviews[i] = new Object[] { i + 1, review.getText(),
					review.getVotes().getUseful(),
					review.getVotes().getFunny(), review.getVotes().getCool(),
					review.getStars() };
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelWord = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemRestart = new javax.swing.JMenuItem();
		jMenuItemTopics = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelWord.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		if (word != null) {
			jLabelWord.setText(word.word);
		} else {
			jLabelWord.setText("Word");	
		}

		jTable1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		tableModel = new javax.swing.table.DefaultTableModel(reviews,
				new String[] { "#", "Review", "Useful votes", "Funny votes",
				"Cool votes", "Stars" });
		jTable1.setModel(tableModel);
		// jTable1.getColumnModel().getColumn(1).setCellRenderer(new
		// ReviewRowRenderer());

		jScrollPane1.setViewportView(jTable1);

		jMenu1.setText("File");

		jMenuItemTopics.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jMenuItemTopics.setText("Show topics");
		jMenuItemTopics.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemTopicsActionPerformed(evt);
			}
		});
		if (allReviews) {
			jMenu1.add(jMenuItemTopics);
		}

		jMenuItemRestart.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jMenuItemRestart.setText("Restart");
		jMenuItemRestart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemRestartActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemRestart);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		if (allReviews) {
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
					getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(layout.createParallelGroup(
					javax.swing.GroupLayout.Alignment.LEADING).addGroup(
					layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jScrollPane1,
									javax.swing.GroupLayout.DEFAULT_SIZE, 586,
									Short.MAX_VALUE).addContainerGap()));
			layout.setVerticalGroup(layout.createParallelGroup(
					javax.swing.GroupLayout.Alignment.LEADING).addGroup(
					javax.swing.GroupLayout.Alignment.TRAILING,
					layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jScrollPane1,
									javax.swing.GroupLayout.DEFAULT_SIZE, 297,
									Short.MAX_VALUE).addContainerGap()));

		} else {
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
					getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(layout
					.createParallelGroup(
							javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addContainerGap()
									.addGroup(
											layout.createParallelGroup(
													javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(
															jScrollPane1,
															javax.swing.GroupLayout.Alignment.TRAILING,
															javax.swing.GroupLayout.DEFAULT_SIZE,
															586,
															Short.MAX_VALUE)
													.addGroup(
															javax.swing.GroupLayout.Alignment.TRAILING,
															layout.createSequentialGroup()
																	.addGap(0,
																			0,
																			Short.MAX_VALUE)
																	.addComponent(
																			jLabelWord)
																	.addGap(0,
																			0,
																			Short.MAX_VALUE)))
									.addContainerGap()));
			layout.setVerticalGroup(layout
					.createParallelGroup(
							javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addContainerGap()
									.addComponent(jLabelWord)
									.addPreferredGap(
											javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(
											jScrollPane1,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											294, Short.MAX_VALUE)
									.addContainerGap()));

		}

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void updateRowHeights() {
		for (int row = 0; row < jTable1.getRowCount(); row++) {
			int rowHeight = jTable1.getRowHeight();

			Component comp = jTable1.prepareRenderer(
					jTable1.getCellRenderer(row, 1), row, 1);
			rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);

			jTable1.setRowHeight(row, rowHeight);
		}
	}

	private void resizeColumns() {
		float[] columnWidthPercentage = { 10.0f, 50.0f, 10.0f, 10.0f, 10.0f,
				10.0f };
		int tW = jTable1.getWidth();
		TableColumn column;
		TableColumnModel jTableColumnModel = jTable1.getColumnModel();
		int cantCols = jTableColumnModel.getColumnCount();
		for (int i = 0; i < cantCols; i++) {
			column = jTableColumnModel.getColumn(i);
			int pWidth = Math.round(columnWidthPercentage[i] * tW);
			column.setPreferredWidth(pWidth);
		}
	}

	private void jMenuItemRestartActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.restart(this);
	}

	private void jMenuItemTopicsActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showWords(this, reviewsArr);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// // <editor-fold defaultstate="collapsed"
	// // desc=" Look and feel setting code (optional) ">
	// /*
	// * If Nimbus (introduced in Java SE 6) is not available, stay with the
	// * default look and feel. For details see
	// * http://download.oracle.com/javase
	// * /tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
	// .getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(Reviews.class.getName()).log(
	// java.util.logging.Level.SEVERE, null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(Reviews.class.getName()).log(
	// java.util.logging.Level.SEVERE, null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(Reviews.class.getName()).log(
	// java.util.logging.Level.SEVERE, null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(Reviews.class.getName()).log(
	// java.util.logging.Level.SEVERE, null, ex);
	// }
	// // </editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new Reviews().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabelWord;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemRestart;
	private javax.swing.JMenuItem jMenuItemTopics;
	// End of variables declaration
}
